pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/artisantek/jenkins.git'
            }
        }

        stage('Tests') {
            parallel {
                stage('Unit Tests') {
                    steps {
                        dir('javaapp-pipeline') {
                            sh 'mvn clean test'
                        }
                    }
                }
                stage('Trivy Scan') {
                    steps {
                        dir('javaapp-pipeline') {
                            sh '''
                                wget -q https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl -O html.tpl
                                trivy fs --format template --template "@html.tpl" -o report.html .
                            '''
                        }
                    }
                }
            }
        }

        stage('Build') {
            steps {
                dir('javaapp-pipeline') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Publish') {
            steps {
                script {
                    def GROUP_ID = sh(script: "mvn help:evaluate -Dexpression=project.groupId -q -DforceStdout -f javaapp-pipeline/pom.xml", returnStdout: true).trim()
                    def ARTIFACT_ID = sh(script: "mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout -f javaapp-pipeline/pom.xml", returnStdout: true).trim()
                    def VERSION = sh(script: "mvn help:evaluate -Dexpression=project.version -q -DforceStdout -f javaapp-pipeline/pom.xml", returnStdout: true).trim()

                    def GROUP_PATH = GROUP_ID.replace('.', '/')
                    def JAR_NAME = "${ARTIFACT_ID}-${VERSION}.jar"

                    echo "JAR_NAME: ${JAR_NAME}"

                    dir('javaapp-pipeline/target') {
                        sh 'ls -l'

                        rtUpload(
                            serverId: 'jfrog-server',
                            spec: """{
                                "files": [
                                    {
                                        "pattern": "${JAR_NAME}",
                                        "target": "maven-repo/${GROUP_PATH}/${ARTIFACT_ID}/${VERSION}/"
                                    }
                                ]
                            }"""
                        )
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    def ARTIFACT_ID = sh(script: "mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout -f javaapp-pipeline/pom.xml", returnStdout: true).trim()
                    def VERSION = sh(script: "mvn help:evaluate -Dexpression=project.version -q -DforceStdout -f javaapp-pipeline/pom.xml", returnStdout: true).trim()

                    def JAR_NAME = "${ARTIFACT_ID}-${VERSION}.jar"

                    dir('javaapp-pipeline/target') {
                        sh """
                            if pgrep -f "java -jar ${JAR_NAME}" > /dev/null; then
                                pkill -f "java -jar ${JAR_NAME}"
                                echo "App was running and has been killed."
                            else
                                echo "App is not running."
                            fi

                            JENKINS_NODE_COOKIE=dontKillMe nohup java -jar ${JAR_NAME} > app.log 2>&1 &
                        """
                    }
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        failure {
            emailext attachLog: true,
                     body: 'Pipeline Failed, Please check the logs',
                     subject: 'Job Failed',
                     to: 'ajayr.akula@gmail.com'
        }
    }
}
